name: token_generator
version: 0.1.0
publish_to: none
description: WDS JSON -> Dart 코드 생성기
environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  args: ^2.5.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0

executables:
  wds_tokens: bin/main.dart
