name: wds_components
version: 0.1.2
publish_to: none
description: WINC Design System components package
environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  wds_foundation:
    path: ../foundation

dev_dependencies:
  flutter_lints: ^6.0.0