name: wds_components
version: 0.1.2
publish_to: "none"
description: WINC Design System components package
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  wds_foundation:
    path: ../foundation

dev_dependencies:
  flutter_lints: ^5.0.0