name: wds_foundation
version: 0.1.0
publish_to: none
description: WINC Design System foundation package
environment:
  sdk: ^3.10.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  intl: ^0.20.2
  meta: ^1.14.0
  wds_tokens:
    path: ../tokens

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/
    - assets/vector/
    - assets/vector/order_status/
