name: wds_widgetbook
version: 0.1.0
publish_to: "none"
description: WINC Design System widgetbook package
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  wds:
    path: ../..
  wds_components:
    path: ../components
  wds_foundation:
    path: ../foundation
  wds_tokens:
    path: ../tokens
  widgetbook: ^3.16.0
  widgetbook_annotation: ^3.7.0
  widgetbook_size_inspector: ^0.0.1

dev_dependencies:
  build_runner: ^2.7.0
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.16.0

flutter:
  uses-material-design: true
  fonts:
    - family: Pretendard
      fonts:
        - asset: packages/wds_foundation/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: packages/wds_foundation/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: packages/wds_foundation/fonts/Pretendard-Regular.ttf
          weight: 400
