name: winc_demo
description: "A demo project for WDS"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  wds_components:
    path: ../../
  wds_foundation:
    path: ../../../foundation

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Pretendard
      fonts:
        - asset: packages/wds_foundation/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: packages/wds_foundation/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: packages/wds_foundation/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: packages/wds_foundation/fonts/Pretendard-Regular.ttf
          weight: 400